[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alma"
version = "1.0.0"
dependencies = [
    "requests",
    "python-dotenv",
    "langchain", 
    "llama-index",
]

[project.scripts]
alma = "alma.core.alma:main"
alma-embeddings = "alma.scripts.embedding_generator:main"

[tool.setuptools]
packages = ["alma", "alma.core", "alma.scripts"]
package-dir = {"" = "src"}