[project]
name = "alma"
version = "1.0.0"
dependencies = [
    "requests",
    "numpy",
    "langchain",
    "llama-index",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"