[project]
name = "alma"
version = "1.0.0"
dependencies = [
    "requests",
    "numpy", 
    "langchain",
    "llama-index",
    "torch",
    "transformers",
]

[project.scripts]
alma = "alma.__main__:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"