[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alma"
version = "1.0.0"
dependencies = [
    "requests",
    "python-dotenv",
    "numpy",
]

[project.scripts]
alma = "alma.__main__:main"

[tool.setuptools]
packages = ["alma", "alma.core"]
package-dir = {"" = "src"}